// <auto-generated />
using System;
using IntermediateTest2.Infra.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace IntermediateTest2.Service.Api.Migrations
{
    [DbContext(typeof(ContextEf))]
    partial class ContextEfModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("IntermediateTest2")
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("IntermediateTest2.Domain.Entities.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime");

                    b.Property<decimal>("MonthlySalary")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("EmployeeId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("IntermediateTest2.Domain.Entities.InflationAdjust", b =>
                {
                    b.Property<int>("InflationAdjustId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AdjustmentDate")
                        .HasColumnType("datetime");

                    b.Property<decimal>("Percentage")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("InflationAdjustId");

                    b.ToTable("InflationAdjusts");
                });

            modelBuilder.Entity("IntermediateTest2.Domain.Entities.SharedFund", b =>
                {
                    b.Property<int>("SharedFundId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("ContributionDate")
                        .HasColumnType("datetime");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("SharedFundId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("SharedFunds");
                });

            modelBuilder.Entity("IntermediateTest2.Domain.Entities.SharedFund", b =>
                {
                    b.HasOne("IntermediateTest2.Domain.Entities.Employee", "Employee")
                        .WithMany("SharedFunds")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
